sudo: required

language: php
matrix:
  fast_finish: true
  include:
  - php: 7.2

services:
  - docker
  
install:
- docker-compose build
- docker-compose up -d

script:
- docker exec interviewv1_server_1 /bin/sh -c 'composer update'
- docker exec interviewv1_server_1 /bin/sh -c 'composer validate --strict'
