version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - "3311:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app1
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql

  server:
    build:
      context: .
      args:
        STABILITY: stable
    volumes:
      # Comment out the next line in production
      - ./server:/srv/server:rw

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    depends_on:
      - server
    volumes:
      # Comment out the next line in production
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./server/public:/srv/server/public:ro
    ports:
      - '8000:80'

  # This HTTP/2 proxy is not secure: it should only be used in dev
  h2-proxy:
    build:
      context: .
      dockerfile: ./Dockerfile.h2-proxy
    volumes:
      - ./docker/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
    ports:
      - '443:443'

  # For development purposes
  adminer:
    image: adminer
    ports:
      - 8080:8080